### DISCUSSION TITLE
Running the PoC on Docker Desktop + WSL

### DISCUSSION THREAD

**Discussion by frankcorneliusmartin** [vantage6/v6-on-kubernetes-PoC#5] [Show and tell]
I needed to make a few changes to run the demo on Docker desktop on Windows.

1. Enable Kubernetes in the settings of Docker desktop / install `kubectl`
2. To get the Kubernetes Dashboard (requires [cert-manager](https://cert-manager.io/docs/installation/) and [nginx-ingress-controller](https://docs.nginx.com/nginx-ingress-controller/installation/)): 

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.1/cert-manager.yaml 
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v3.0.0-alpha0/charts/kubernetes-dashboard.yaml
```

3. Bind the dashboard to localhost:

```bash
kubectl -n ingress-nginx port-forward svc/ingress-nginx-controller 8443:443
```

4. Generate access token 
```bash
kubectl get secret admin-user -n kubernetes-dashboard -o jsonpath={".data.token"} | base64 -d
```

Now you can login at `https://localhost` with this token.

5. Change the mount paths. In order to access the files in the hostmachine you have to use the `/run/desktop/mnt/host/c` path. (see [stack overflow](https://stackoverflow.com/questions/66985465/kubernetes-how-to-correctly-mount-windows-path-in-wsl2-backed-environment) for more details)
  
   * I moved the *v6-node-config-file* (`node_config.yaml`) and *kube-config-file* (`config`) to my `c:/data/k8s` folder so I would be able to mount them. The `node_pod_config` then becomes: 
   
```yaml
apiVersion: v1
kind: Pod
metadata:
 name: poc-node-pod
spec:
 containers:
 ...

 volumes:
 - name: task-files-root
   hostPath:
     path: /home/frank/tmp/tasks
 - name: kube-config-file
   hostPath:
     path: /run/desktop/mnt/host/c/data/k8s/config
 - name: v6-node-config-file
   hostPath:
     path: /run/desktop/mnt/host/c/data/k8s/node_config.yaml
```

6. I had difficulties finding the right IP settings as the routing was a bit unclear to me (because my lack of Kubernetes/windows experience), therefore I changed that the server listens to interface `0.0.0.0`. Thus `server_config.yaml` becomes: 

```yaml
# IP address of the adapter where the server will be listening to
server_ip: 0.0.0.0

# port
port: 5000
```

7. Run the server on the windows machine (not in the WSL instance): `python simple_sio_server.py`
8. I had to change the host IP in the node config to `host.docker.internal` in order to reach my simple server in my windows system:

```yaml
apiVersion: v1
kind: Pod
metadata:
 name: poc-node-pod
spec:
 containers:
 - name: dummy-node-server
   image: docker.io/hectorcadavid/dummy-node-x86:latest
   tty: true
   env:
   - name: HOST_IP
     value: host.docker.internal
   command: ["python", "node.py"]
   volumeMounts:
   - name: task-files-root
     mountPath: /app/tasks
   - name: kube-config-file
     mountPath: /app/.kube/config
   - name: v6-node-config-file
     mountPath: /app/.v6node/node_config.yaml
volumes: 
  ...
```

9. Change the IP in the `command_emmiter.py` to the IP the server listens on. From windows `localhost` should do, if you want to run it from your WSL instance you need to use the WSL interface at your hostmachine. In powershell: `ipconfig` and look for the WSL adapter.
