### DISCUSSION TITLE
Running the PoC on microk8s + MacOS (M1, arm64)

### DISCUSSION THREAD

**Discussion by CunliangGeng** [vantage6/v6-on-kubernetes-PoC#6] [Show and tell]
## Some background

|  | Linux | MacOS | Windows 10 & 11 |
| ---- | ---- | ---- | ---- |
| containerization support | The Linux kernel supports containerization [natively with features like namespaces and cgroups.](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/containerd) | macOS does not natively support containerization. | Windows support containerzation using<br>- WSL (Linux kernel)<br>- or Hyper-V to create Linux VM |
| Docker | Using native Linux features (no VM) for container support | Using Linux VM for container support | Using WSL or Hyper-V (VM) for container support.<br><br>Using Hyper-V can enable support for Windows-based containers. |
| Microk8s | Using Linux native features (no VM) | Using ubuntu VM for container support, created by [multipass](https://multipass.run/) (through [QEMU](https://www.qemu.org/) -> [Virtualization.Framework](https://developer.apple.com/documentation/virtualization)) | Using ubuntu VM for container support, created by multipass (through [Hyper-V](i)) |

So note that k8s of microk8s runs in a VM on MacOS and Windows.

## Multiarch images

The multiarch (amd64, arm64, arm) images are available on dockerhub:
- `clgeng/dummy_v6_node`
- `clgeng/v6_average_algorithm` 

## Some changes to run PoC on MacOS (Arm64) using microk8s

1. Mount the repo to `microk8s-vm` VM after microk8s starts

```
 # on Mac
 cd v6-on-kubernetes-PoC
 multipass mount . microk8s-vm:/home/ubuntu/v6-on-kubernetes-PoC
```

2. After mounting, you can login the VM (`microk8s-vm`) and then do all operations in the VM.
3. Run dummy v6 server in the VM (`microk8s-vm`). Running v6 server directly on MacOS will make v6 node failed to connect due to network issue.

The IP address for v6 server can be set to the IP of the VM. The VM IP can be found using `multipass ls` command on Mac or displayed when login to the VM:
  
```
# login VM
multipass shell microk8s-vm

# do the following in VM
cd v6-on-kubernetes-PoC

python -m venv venv
source venv/bin/activate
pip install -r requirements.txt

cd dummy_socketio_server
python simple_sio_server.py
```

4. `$HOME/.kube/config` is not found in the VM (neither in Mac). You need to create one.

``` 
cd v6-on-kubernetes-PoC
sudo microk8s config > config
```

5. Since VM is the host machine of k8s, so updating `node_config.yaml` and `node_pod_config.yaml` to use VM's paths.

**node_config.yaml**
```
databases:
  - label: default
    uri: /home/ubuntu/v6-on-kubernetes-PoC/csv/employees.csv
    type: csv

task_dir: /home/ubuntu/tasks
```

**node_pod_config.yaml**

`PORT` value is the same as the port number for v6 server set in `server_config.yaml`.

```
   - name: PORT
     value: "5000"

 volumes:
 - name: task-files-root
   hostPath:
     path: /home/ubuntu/tasks
 - name: kube-config-file
   hostPath:
     path: /home/ubuntu/v6-on-kubernetes-PoC/config
 - name: v6-node-config-file
   hostPath:
     path: /home/ubuntu/v6-on-kubernetes-PoC/node_poc/node_config.yaml
```

## Microk8s problem on MacOS

If your Mac restarts when microk8s is running, microk8s will still be running after your Mac is on. However,  microk8s will not be started any more if it's stopped. And you cannot create new VMs using multipass. The restarted or new VMs will get a `unknown` state.

### How to solve this problem?
1. Stop or suspend all VMs using command `multipass stop --all`
2. Remove DHCP lease file `sudo rm /var/db/dhcpd_leases`
3. Create a empty DHCP lease file `sudo touch /var/db/dhcpd_leases`
4. Restart your Mac

If this method does not work for you, check https://multipass.run/docs/troubleshoot-networking#heading--issues-caused-by-macos-update.

### How to avoid this problem?
Quite simple: suspend or stop all multipass VMs before shutdowning or restarting your Mac.
